### ISSUE TITLE
Gold price

### ISSUE THREAD

**Issue by sainiaj** [mykle1/MMM-LICE#2]
Hi can you please add the current gold price

i really love your module thinking about purchasing a plan 

at the moment it is USDXAU meaning how much gold can you get for 1 USD dollar =0.000something79
when it should be XAUUSD how much USD will you get for 1 gold (default is ounce)  = 1,275.55

Thank you once again for this awesome module,

do you know any other free api to get live/current gold price upto 15 minutes delay is fine

**Comment by mykle1** [comment]
Glad you like the module. If you upgrade your currencylayer.com account from the free account you can then use XAU as your SOURCE CURRENCY. This module is designed around the free account Peace!
